@extends('layout.app')
@extends('admin.nav')
@extends('admin.saidebar')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Sales Coordinator Dashboard</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            
            <!-- Welcome Alert -->
             <!--
            <div class="row mb-3">
                <div class="col-12">
                    <div class="alert alert-info alert-dismissible fade show shadow-sm" role="alert">
                        <h5><i class="icon fas fa-info-circle"></i> Welcome, {{ Auth::user()->name }}!</h5>
                        You are logged in as a <strong>Sales Coordinator</strong>. From here, you can view sales reports, export them, and import the data for the Support Team.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
-->

            <!-- Dashboard Widgets (Quick Links based on sidebar access) -->
            <div class="row">
                
                <!-- 1. All Agent Sales Reports -->
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-success shadow">
                        <div class="inner">
                            <h3>Sales</h3>
                            <p>All Agent Sales Reports</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-dollar-sign"></i>
                        </div>
                        <a href="{{ route('viewAgentSaleTable') }}" class="small-box-footer">
                            View Reports <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>

                <!-- 2. Import Support Data -->
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-info shadow">
                        <div class="inner">
                            <h3>Import</h3>
                            <p>Import Data to Support</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-file-import"></i>
                        </div>
                        <a href="{{ route('support.import') }}" class="small-box-footer">
                            Upload Excel <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>

                <!-- 3. Expired Supports -->
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-danger shadow">
                        <div class="inner">
                            <h3>Expired</h3>
                            <p>Manage Expired Supports</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-clock-rotate-left"></i>
                        </div>
                        <a href="{{ route('support.expired') }}" class="small-box-footer">
                            View Expired <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>

            </div>

            <!-- Workflow Guide Card -->
            <div class="row mt-4">
                <div class="col-12">
                    <div class="card shadow">
                        <div class="card-header bg-primary text-white">
                            <h3 class="card-title"><i class="fas fa-briefcase"></i> Your Workflow Guide</h3>
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush text-muted">
                                <li class="list-group-item">
                                    <strong>Step 1:</strong> Go to <a href="{{ route('viewAgentSaleTable') }}" class="text-primary font-weight-bold">All Agent Sales Reports</a> to view the sales generated by agents.
                                </li>
                                <li class="list-group-item">
                                    <strong>Step 2:</strong> Use the export options (CSV/Excel) on the data table to download the sales data.
                                </li>
                                <li class="list-group-item">
                                    <strong>Step 3:</strong> Go to <a href="{{ route('support.import') }}" class="text-info font-weight-bold">Import Data</a> under the Support Team section and upload the Excel file to assign data to support.
                                </li>
                                <li class="list-group-item">
                                    <strong>Step 4:</strong> Check <a href="{{ route('support.expired') }}" class="text-danger font-weight-bold">Expired Supports</a> to monitor and re-assign any expired customer entries.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div>
@endsection